### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by momer** [Ectelion/facial-expression-recognition#1]
Nice work! I'm interested in taking a look through the code to see what I can learn as I work on my own projects, but I can't open a single file until there's a license associated with the project. Have you considered adding something copyleft?

Github has put together [a pretty neat website](http://choosealicense.com/) for helping you select a license if you're interested. 

At the moment, the code is online, but it's 100% copyright attributed to you with all rights reserved (legal default when no license is displayed). 

Thank you for your contributions!

Mo

**Comment by Ectelion** [comment]
Hi Mo,

My excuses for the delayed response -- I was in a trip for a while. 

I have specified the license: I guess, the choice of GNU provides a reasonable tradeoff between freedom of use and some of my further plans. Hopefully, that works out for your needs as well :)

Thanks for your feedback and suggestions! 

Best,
Rustem

**Comment by momer** [comment]
That's great, thank you,

Mo
